version: "3"
services:
  nginx:
    restart: always
    build: ./nginx
    ports:
      - 7777:80
    depends_on:
      - web
    links:
      - web
    networks:
      - frontend
  web:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    #expose:
    #  - 8000
    env_file:
      - production.env
    depends_on:
      - db
    networks:
      - frontend
      - backend
  db:
    restart: always
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - db.env
    volumes:
      - /opt/puzzle-mysql:/var/lib/mysql
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
